<?php
$auto_reviews_en = array(
    array("name" => "Luke M.", "text" => "The boxers keep their shape even after many washes."),
    array("name" => "James P.", "text" => "Soft fabric, nothing scratches or pinches."),
    array("name" => "David S.", "text" => "Very comfortable all day, I barely notice them."),
    array("name" => "Tim R.", "text" => "The waistband holds firm but doesn't dig in."),
    array("name" => "Felix D.", "text" => "Breathable and light, perfect for everyday and workouts."),
    array("name" => "Leo K.", "text" => "They stay in shape even after several washes."),
    array("name" => "Patrick C.", "text" => "Comfortable on skin and no annoying seams."),
    array("name" => "Mark V.", "text" => "Even after a long day everything stays in place."),
    array("name" => "Rob L.", "text" => "They feel premium the moment you pick them up."),
    array("name" => "Nick G.", "text" => "No stretching out, no shifting, just comfortable."),
    array("name" => "Seb B.", "text" => "Great cut, fits well without being too tight."),
    array("name" => "Flo J.", "text" => "The legs don't ride up, big plus."),
    array("name" => "Matt S.", "text" => "The fabric breathes well and stays comfortably dry."),
    array("name" => "Dennis K.", "text" => "Very cleanly made and look long-lasting."),
    array("name" => "Kevin H.", "text" => "Price-to-quality ratio is really strong."),
    array("name" => "Tom N.", "text" => "Fit well even when you're between two sizes."),
    array("name" => "Andy M.", "text" => "Ideal for work and sport, I barely wear any others."),
    array("name" => "Len B.", "text" => "Very comfortable even during long hours sitting at a desk."),
    array("name" => "Simon Z.", "text" => "No irritation, even on warm days."),
    array("name" => "Ben F.", "text" => "Tried them once and immediately ordered more pairs."),
);
